apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: otelcol-kafka-consumer
  namespace: confluent-kafka

namespace: confluent-kafka

resources:
- rbac.yaml
- otelcol-config.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- network-policy.yaml

commonLabels:
  app: otelcol
  component: kafka-consumer
  version: v0.97.0

replicas:
- name: otelcol-kafka-consumer
  count: 2

images:
- name: otel/opentelemetry-collector-contrib
  newTag: 0.97.0

configMapGenerator:
- name: otelcol-env-config
  literals:
  - KAFKA_CLUSTER_NAME=kafka-cluster
  - GRAFANA_TENANT_ID=tenant1
  - OTEL_LOG_LEVEL=info
  - OTEL_RESOURCE_ATTRIBUTES=service.name=otelcol-kafka-consumer,service.version=0.97.0

patches:
# 根据环境调整资源限制
- target:
    kind: Deployment
    name: otelcol-kafka-consumer
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "1Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "256Mi"

# 根据需要调整副本数
- target:
    kind: Deployment
    name: otelcol-kafka-consumer
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2 