apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-simple
  namespace: confluent-kafka
data:
  config.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024

      memory_limiter:
        check_interval: 1s
        limit_mib: 256

    exporters:
      debug:
        verbosity: detailed
      
      logging:
        loglevel: info
        
      prometheus:
        endpoint: "0.0.0.0:8889"

    service:
      extensions: [health_check]
      
      pipelines:
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug, logging]

        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug, prometheus]

        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug, logging]

      telemetry:
        logs:
          level: "info"
        metrics:
          address: 0.0.0.0:8888 