apiVersion: v1
kind: ServiceAccount
metadata:
  name: otelcol-kafka-consumer
  namespace: confluent-kafka
  labels:
    app: otelcol
    component: kafka-consumer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otelcol-kafka-consumer
  labels:
    app: otelcol
    component: kafka-consumer
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods", "events", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["replicasets", "deployments", "daemonsets", "statefulsets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions"]
  resources: ["replicasets", "deployments", "daemonsets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otelcol-kafka-consumer
  labels:
    app: otelcol
    component: kafka-consumer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otelcol-kafka-consumer
subjects:
- kind: ServiceAccount
  name: otelcol-kafka-consumer
  namespace: confluent-kafka 