apiVersion: v1
kind: Namespace
metadata:
  name: confluent-kafka
  labels:
    name: confluent-kafka
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kafka-resource-quota
  namespace: confluent-kafka
spec:
  hard:
    requests.cpu: "12"
    requests.memory: 24Gi
    limits.cpu: "24"
    limits.memory: 48Gi
    persistentvolumeclaims: "10"
    requests.storage: 1Ti
---
apiVersion: v1
kind: LimitRange
metadata:
  name: kafka-limit-range
  namespace: confluent-kafka
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "1"
      memory: "2Gi"
    type: Container 