apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-server-cert
  namespace: kafka
spec:
  secretName: kafka-server-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: kafka-server
  dnsNames:
  - kafka-service
  - kafka-service.kafka.svc.cluster.local
  - kafka-headless
  - kafka-headless.kafka.svc.cluster.local
  - kafka-0.kafka-headless
  - kafka-0.kafka-headless.kafka.svc.cluster.local
  - localhost
  ipAddresses:
  - 127.0.0.1
  duration: 8760h # 1年
  renewBefore: 720h # 30天前续期
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zookeeper-server-cert
  namespace: kafka
spec:
  secretName: zookeeper-server-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: zookeeper-server
  dnsNames:
  - zookeeper-service
  - zookeeper-service.kafka.svc.cluster.local
  - zookeeper-headless
  - zookeeper-headless.kafka.svc.cluster.local
  - zookeeper-0.zookeeper-headless
  - zookeeper-0.zookeeper-headless.kafka.svc.cluster.local
  - localhost
  ipAddresses:
  - 127.0.0.1
  duration: 8760h # 1年
  renewBefore: 720h # 30天前续期
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-client-cert
  namespace: kafka
spec:
  secretName: kafka-client-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: kafka-client
  duration: 8760h # 1年
  renewBefore: 720h # 30天前续期 