apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: kafka
  labels:
    app: kafka-client
spec:
  initContainers:
  - name: cert-converter
    image: openjdk:11-jre-slim
    command:
    - /bin/bash
    - -c
    - |
      apt-get update && apt-get install -y openssl
      
      # 创建客户端证书目录
      mkdir -p /etc/kafka/secrets/kafka-client-tls
      
      # 转换客户端证书为JKS格式
      openssl pkcs12 -export -in /etc/certs/tls.crt -inkey /etc/certs/tls.key \
        -out /tmp/client-keystore.p12 -name kafka-client -passout pass:changeit
      
      keytool -importkeystore -deststorepass changeit -destkeypass changeit \
        -destkeystore /etc/kafka/secrets/kafka-client-tls/keystore.jks \
        -srckeystore /tmp/client-keystore.p12 -srcstoretype PKCS12 -srcstorepass changeit
      
      # 创建客户端truststore并导入CA证书
      keytool -import -trustcacerts -alias ca-cert -file /etc/ca-certs/ca.crt \
        -keystore /etc/kafka/secrets/kafka-client-tls/truststore.jks \
        -storepass changeit -noprompt
    volumeMounts:
    - name: kafka-client-certs
      mountPath: /etc/certs
    - name: ca-certs
      mountPath: /etc/ca-certs
    - name: cert-storage
      mountPath: /etc/kafka/secrets
  containers:
  - name: kafka-client
    image: confluentinc/cp-kafka:7.4.0
    command: ["/bin/bash"]
    args: ["-c", "sleep 3600"]
    volumeMounts:
    - name: cert-storage
      mountPath: /etc/kafka/secrets
    - name: client-config
      mountPath: /etc/kafka/client.properties
      subPath: client.properties
    env:
    - name: KAFKA_OPTS
      value: "-Djava.security.auth.login.config=/etc/kafka/client.properties"
  volumes:
  - name: kafka-client-certs
    secret:
      secretName: kafka-client-tls
  - name: ca-certs
    secret:
      secretName: kafka-ca-secret
  - name: cert-storage
    emptyDir: {}
  - name: client-config
    configMap:
      name: kafka-client-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-client-config
  namespace: kafka
data:
  client.properties: |
    # Kafka客户端SSL配置
    security.protocol=SSL
    ssl.truststore.location=/etc/kafka/secrets/kafka-client-tls/truststore.jks
    ssl.truststore.password=changeit
    ssl.keystore.location=/etc/kafka/secrets/kafka-client-tls/keystore.jks
    ssl.keystore.password=changeit
    ssl.key.password=changeit
    ssl.enabled.protocols=TLSv1.2,TLSv1.3
    ssl.keystore.type=JKS
    ssl.truststore.type=JKS
    
    # 生产者配置
    bootstrap.servers=kafka-service:9093
    acks=all
    retries=3
    batch.size=16384
    linger.ms=1
    buffer.memory=33554432
    key.serializer=org.apache.kafka.common.serialization.StringSerializer
    value.serializer=org.apache.kafka.common.serialization.StringSerializer
    
    # 消费者配置
    group.id=test-consumer-group
    enable.auto.commit=true
    auto.commit.interval.ms=1000
    session.timeout.ms=30000
    key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
    value.deserializer=org.apache.kafka.common.serialization.StringDeserializer 