# 3节点Kafka集群配置
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-ha
  namespace: kafka
  labels:
    app: kafka-ha
spec:
  serviceName: kafka-ha-headless
  replicas: 3
  selector:
    matchLabels:
      app: kafka-ha
  template:
    metadata:
      labels:
        app: kafka-ha
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.4.0
        ports:
        - containerPort: 9092
          name: plaintext
        - containerPort: 9999
          name: jmx
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-ha-service:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "2"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "2"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "false"
        - name: KAFKA_DELETE_TOPIC_ENABLE
          value: "true"
        - name: KAFKA_JMX_PORT
          value: "9999"
        - name: KAFKA_JMX_HOSTNAME
          value: "localhost"
        command:
        - /bin/bash
        - -c
        - |
          # 等待Zookeeper就绪
          echo "Waiting for Zookeeper..."
          until nc -z zookeeper-ha-service 2181; do
            echo "Waiting for Zookeeper to be ready..."
            sleep 5
          done
          echo "Zookeeper is ready!"
          
          # 从Pod名称提取broker ID
          BROKER_ID=${HOSTNAME##*-}
          echo "Setting KAFKA_BROKER_ID to: $BROKER_ID"
          export KAFKA_BROKER_ID=$BROKER_ID
          
          # 动态设置advertised listeners
          export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://${HOSTNAME}.kafka-ha-headless:9092"
          echo "Setting KAFKA_ADVERTISED_LISTENERS to: $KAFKA_ADVERTISED_LISTENERS"
          
          # 启动Kafka
          exec /etc/confluent/docker/run
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi 