apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: tempo
data:
  tempo.yaml: |
    server:
      http_listen_port: 3100

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
            http:

    ingester:
      trace_idle_period: 10s
      max_block_bytes: 100_000_000
      max_block_duration: 5m

    compactor:
      compaction:
        block_retention: 24h

    storage:
      trace:
        backend: gcs
        gcs:
          bucket_name: tempo-trace-bucket-1750119369 