# TLS证书Secret配置模板
# 实际证书需要通过scripts/generate-certs.sh生成
apiVersion: v1
kind: Secret
metadata:
  name: kafka-tls-certs
  namespace: confluent-kafka
type: Opaque
data:
  # CA证书 - base64编码
  ca.crt: LS0tLS1CRUdJTi... # 这里将被实际的CA证书替换
  # Kafka服务器证书
  kafka.crt: LS0tLS1CRUdJTi... # 这里将被实际的Kafka证书替换
  # Kafka服务器私钥
  kafka.key: LS0tLS1CRUdJTi... # 这里将被实际的私钥替换
  # 客户端证书
  client.crt: LS0tLS1CRUdJTi... # 这里将被实际的客户端证书替换
  # 客户端私钥
  client.key: LS0tLS1CRUdJTi... # 这里将被实际的客户端私钥替换
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-keystore
  namespace: confluent-kafka
type: Opaque
data:
  # Java KeyStore文件 - base64编码
  kafka.server.keystore.jks: UEsDBAoAAA... # 这里将被实际的keystore替换
  # Java TrustStore文件
  kafka.server.truststore.jks: UEsDBAoAAA... # 这里将被实际的truststore替换
  # KeyStore密码
  keystore-password: cGFzc3dvcmQ= # 默认密码"password"的base64编码
  # TrustStore密码
  truststore-password: cGFzc3dvcmQ= # 默认密码"password"的base64编码 