apiVersion: v1
kind: ServiceMonitor
metadata:
  name: kafka-metrics
  namespace: confluent-kafka
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  endpoints:
  - port: jmx
    interval: 30s
    path: /metrics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-jmx-config
  namespace: confluent-kafka
data:
  jmx_prometheus_javaagent.yml: |
    rules:
    # Kafka broker metrics
    - pattern: kafka.server<type=(.+), name=(.+)><>Value
      name: kafka_server_$1_$2
      type: GAUGE
    - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+)><>Value
      name: kafka_server_$1_$2
      type: GAUGE
      labels:
        clientId: "$3"
    - pattern: kafka.server<type=(.+), name=(.+), topic=(.+)><>Value
      name: kafka_server_$1_$2
      type: GAUGE
      labels:
        topic: "$3"
    - pattern: kafka.server<type=(.+), name=(.+), topic=(.+), partition=(.+)><>Value
      name: kafka_server_$1_$2
      type: GAUGE
      labels:
        topic: "$3"
        partition: "$4"
    
    # Network request metrics
    - pattern: kafka.network<type=RequestMetrics, name=RequestsPerSec, request=(.+)><>Count
      name: kafka_network_requests_per_sec
      type: COUNTER
      labels:
        request: "$1"
    
    # Log metrics
    - pattern: kafka.log<type=LogFlushStats, name=LogFlushRateAndTimeMs><>Count
      name: kafka_log_flush_rate
      type: COUNTER
    
    # Controller metrics
    - pattern: kafka.controller<type=(.+), name=(.+)><>Value
      name: kafka_controller_$1_$2
      type: GAUGE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: confluent-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
      - name: kafka-exporter
        image: danielqsj/kafka-exporter:latest
        args:
        - --kafka.server=kafka:9092
        - --web.listen-address=:9308
        ports:
        - containerPort: 9308
          name: metrics
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: confluent-kafka
  labels:
    app: kafka-exporter
spec:
  ports:
  - port: 9308
    targetPort: 9308
    name: metrics
  selector:
    app: kafka-exporter 