---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki
  namespace: grafana-stack
  labels:
    app: loki
    component: loki
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: loki
      component: loki
  endpoints:
  - port: http-metrics
    interval: 15s
    path: /metrics
    scrapeTimeout: 10s
    # 监控关键的速率指标
    metricRelabelings:
    # 保留重要的Loki指标
    - sourceLabels: [__name__]
      regex: 'loki_(ingester_.*|distributor_.*|querier_.*|query_frontend_.*)'
      action: keep
    # 保留错误率指标
    - sourceLabels: [__name__]
      regex: 'loki_.*_errors_total'
      action: keep
    # 保留延迟指标
    - sourceLabels: [__name__]
      regex: 'loki_.*_duration_seconds.*'
      action: keep
    # 保留队列指标
    - sourceLabels: [__name__]
      regex: 'loki_.*_queue_.*'
      action: keep
    # 保留速率限制指标
    - sourceLabels: [__name__]
      regex: 'loki_.*_rate_.*'
      action: keep
    relabelings:
    # 添加集群标签
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: kubernetes_namespace
    - sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: kubernetes_name
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: kubernetes_pod_name

---
# 创建一个Grafana Dashboard ConfigMap（可选）
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-dashboard
  namespace: grafana-stack
  labels:
    grafana_dashboard: "1"
data:
  loki-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Loki Performance Dashboard",
        "tags": ["loki", "logs"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Ingestion Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "sum(rate(loki_distributor_received_samples_total[5m]))",
                "legendFormat": "Samples/sec"
              }
            ]
          },
          {
            "id": 2,
            "title": "Queue Size",
            "type": "graph",
            "targets": [
              {
                "expr": "loki_ingester_chunks_flushed_total",
                "legendFormat": "Chunks Flushed"
              }
            ]
          },
          {
            "id": 3,
            "title": "Error Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "sum(rate(loki_distributor_errors_total[5m]))",
                "legendFormat": "Errors/sec"
              }
            ]
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "30s"
      }
    } 