---
# ServiceMonitor for Prometheus monitoring
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki-metrics
  namespace: grafana-stack
  labels:
    app: loki
    component: loki
spec:
  selector:
    matchLabels:
      app: loki
      component: loki
  endpoints:
  - port: http-metrics
    interval: 30s
    path: /metrics
    scheme: http
    scrapeTimeout: 10s
    # 生产环境标签
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    metricRelabelings:
    # 删除高基数指标以减少Prometheus负载
    - sourceLabels: [__name__]
      regex: 'loki_distributor_received_samples_total|loki_distributor_samples_received_total'
      action: drop

---
# PrometheusRule for Loki alerts
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: loki-alerts
  namespace: grafana-stack
  labels:
    app: loki
    component: loki
spec:
  groups:
  - name: loki.rules
    interval: 30s
    rules:
    # Loki服务可用性告警
    - alert: LokiDown
      expr: up{job="loki"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Loki实例不可用"
        description: "Loki实例 {{ $labels.instance }} 已经下线超过5分钟"
    
    # 写入错误率告警
    - alert: LokiWriteErrorRate
      expr: |
        (
          rate(loki_distributor_ingester_append_failures_total[5m])
          /
          rate(loki_distributor_ingester_appends_total[5m])
        ) > 0.01
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Loki写入错误率过高"
        description: "Loki写入错误率为 {{ $value | humanizePercentage }}，超过1%"
    
    # 写入延迟告警
    - alert: LokiWriteLatencyHigh
      expr: |
        histogram_quantile(0.99, 
          rate(loki_distributor_ingester_append_duration_seconds_bucket[5m])
        ) > 1
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "Loki写入延迟过高"
        description: "Loki 99%分位数写入延迟为 {{ $value }}s，超过1秒"
    
    # 内存使用率告警
    - alert: LokiMemoryUsageHigh
      expr: |
        (
          process_resident_memory_bytes{job="loki"}
          /
          container_spec_memory_limit_bytes{pod=~"loki-.*"}
        ) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Loki内存使用率过高"
        description: "Loki Pod {{ $labels.pod }} 内存使用率为 {{ $value | humanizePercentage }}，超过80%"
    
    # 写入速率过高告警
    - alert: LokiIngestionRateHigh
      expr: |
        sum(rate(loki_distributor_bytes_received_total[5m])) > 45 * 1024 * 1024
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Loki写入速率接近限制"
        description: "Loki当前写入速率为 {{ $value | humanize1024 }}B/s，接近50MB/s限制"
    
    # WAL replay时间过长告警
    - alert: LokiWALReplayTooSlow
      expr: |
        loki_ingester_wal_replay_duration_seconds > 300
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Loki WAL重放时间过长"
        description: "Loki WAL重放时间为 {{ $value }}s，超过5分钟"
    
    # 查询错误率告警
    - alert: LokiQueryErrorRate
      expr: |
        (
          rate(loki_logql_querystats_total{status_code!~"2.."}[5m])
          /
          rate(loki_logql_querystats_total[5m])
        ) > 0.05
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Loki查询错误率过高"
        description: "Loki查询错误率为 {{ $value | humanizePercentage }}，超过5%"
    
    # GCS存储访问错误
    - alert: LokiGCSErrors
      expr: |
        rate(loki_gcs_request_duration_seconds_count{status_code!~"2.."}[5m]) > 0.1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Loki GCS存储访问错误"
        description: "Loki GCS存储访问错误率为 {{ $value }}/s"
    
    # 压缩器未运行告警
    - alert: LokiCompactorNotRunning
      expr: |
        time() - loki_compactor_last_successful_run_timestamp_seconds > 86400
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Loki压缩器超过24小时未运行"
        description: "Loki压缩器上次成功运行时间：{{ $value | humanizeTimestamp }}"

---
# Grafana Dashboard ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-dashboard
  namespace: grafana-stack
  labels:
    grafana_dashboard: "1"
data:
  loki-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Loki生产环境监控",
        "tags": ["loki", "logging", "production"],
        "style": "dark",
        "timezone": "browser",
        "refresh": "30s",
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "panels": [
          {
            "title": "Loki服务状态",
            "type": "stat",
            "targets": [
              {
                "expr": "up{job=\"loki\"}",
                "legendFormat": "{{instance}}"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "thresholds"
                },
                "thresholds": {
                  "steps": [
                    {"color": "red", "value": 0},
                    {"color": "green", "value": 1}
                  ]
                }
              }
            }
          },
          {
            "title": "写入速率",
            "type": "graph",
            "targets": [
              {
                "expr": "sum(rate(loki_distributor_bytes_received_total[5m]))",
                "legendFormat": "写入速率 (bytes/s)"
              }
            ]
          },
          {
            "title": "内存使用率",
            "type": "graph",
            "targets": [
              {
                "expr": "process_resident_memory_bytes{job=\"loki\"} / 1024 / 1024 / 1024",
                "legendFormat": "{{instance}} 内存 (GB)"
              }
            ]
          },
          {
            "title": "查询延迟",
            "type": "graph",
            "targets": [
              {
                "expr": "histogram_quantile(0.99, rate(loki_request_duration_seconds_bucket{job=\"loki\"}[5m]))",
                "legendFormat": "99%分位数延迟"
              },
              {
                "expr": "histogram_quantile(0.50, rate(loki_request_duration_seconds_bucket{job=\"loki\"}[5m]))",
                "legendFormat": "50%分位数延迟"
              }
            ]
          }
        ]
      }
    } 