---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: loki-hpa
  namespace: grafana-stack
  labels:
    app: loki
    component: loki
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loki
  minReplicas: 3    # 生产环境最小3副本
  maxReplicas: 12   # 生产环境最大12副本
  metrics:
  # CPU使用率
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60  # 降低触发阈值，更早扩容
  # 内存使用率
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70  # 降低内存阈值
  # 基于Pod指标的扩容（如果配置了custom metrics）
  # - type: Pods
  #   pods:
  #     metric:
  #       name: ingestion_rate
  #     target:
  #       type: AverageValue
  #       averageValue: "30"  # 30MB/s per pod
  behavior:
    scaleDown:
      # 保守的缩容策略
      stabilizationWindowSeconds: 600  # 10分钟稳定窗口
      policies:
      - type: Percent
        value: 20  # 每次最多缩容20%
        periodSeconds: 120  # 2分钟间隔
      - type: Pods
        value: 1   # 每次最多减少1个Pod
        periodSeconds: 120
      selectPolicy: Min  # 选择最保守的策略
    scaleUp:
      # 更积极的扩容策略
      stabilizationWindowSeconds: 120  # 2分钟稳定窗口
      policies:
      - type: Percent
        value: 50   # 每次最多扩容50%
        periodSeconds: 60
      - type: Pods
        value: 3    # 每次最多增加3个Pod
        periodSeconds: 60
      selectPolicy: Max  # 选择最积极的策略

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: loki-pdb
  namespace: grafana-stack
  labels:
    app: loki
    component: loki
spec:
  minAvailable: 2    # 生产环境至少保持2个Pod运行
  selector:
    matchLabels:
      app: loki
      component: loki

# 注意：如需启用VPA，请先安装VPA CRDs：
# kubectl apply -f https://github.com/kubernetes/autoscaler/releases/download/vertical-pod-autoscaler-0.13.0/vpa-v1-crd-gen.yaml 