---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: loki-hpa
  namespace: grafana-stack
  labels:
    app: loki
    component: loki
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loki
  minReplicas: 2
  maxReplicas: 8  # 最大副本数，应对突发流量
  metrics:
  # CPU使用率
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # 内存使用率
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      # 缩容策略 - 保守一些
      stabilizationWindowSeconds: 300  # 5分钟稳定窗口
      policies:
      - type: Percent
        value: 25  # 每次最多缩容25%
        periodSeconds: 60
      - type: Pods
        value: 1   # 每次最多减少1个Pod
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      # 扩容策略 - 更积极以应对突发负载
      stabilizationWindowSeconds: 60   # 1分钟稳定窗口
      policies:
      - type: Percent
        value: 100  # 每次最多扩容100%
        periodSeconds: 30
      - type: Pods
        value: 2    # 每次最多增加2个Pod
        periodSeconds: 30
      selectPolicy: Max

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: loki-pdb
  namespace: grafana-stack
  labels:
    app: loki
    component: loki
spec:
  minAvailable: 1  # 至少保持1个Pod运行
  selector:
    matchLabels:
      app: loki
      component: loki 