all:
  children:
    rproxy:
      hosts:
        # 通过Terraform更新的主机会自动添加到这里
        # 或在Tower中直接配置host变量
        
        # 示例配置（实际使用时由Terraform或Tower配置）
        # dev-rproxy-1:
        #   ansible_host: "{{ tower_job_extra_vars.instance_ip | default('127.0.0.1') }}"
        #   ansible_user: "{{ tower_ssh_user | default('stephen_h_zhou') }}"
        #   ansible_ssh_private_key_file: "{{ tower_ssh_key_path | default('~/.ssh/google_compute_engine') }}"
        #   ansible_port: "{{ tower_ssh_port | default(2234) }}"
        #   github_branch: "dev-rproxy-1"
        
  vars:
    # Tower专用变量配置
    ansible_python_interpreter: /usr/bin/python3
    
    # 备份配置 - 可在Tower Job Template中覆盖
    backup_dir: "{{ tower_backup_dir | default('/tmp/apache_backup') }}"
    
    # 通过Tower的Extra Variables或Survey配置这些变量
    # github_repo: 在Tower中配置
    # github_token: 在Tower Credentials中配置
    # git_user_name: 在Tower中配置
    # git_user_email: 在Tower中配置
    
    # SSH配置 - Tower会自动处理
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_ssh_pipelining: yes
    ansible_ssh_timeout: 30 