---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-gcs
  namespace: grafana-stack
  annotations:
    # 将此处的 coral-pipe-457011-d2 替换为您的GCP项目ID
    # 将此处的 loki-storage 替换为您的Google服务账号名称
    iam.gke.io/gcp-service-account: loki-storage@coral-pipe-457011-d2.iam.gserviceaccount.com
  labels:
    app: loki
    component: loki 