apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: confluent-kafka
  labels:
    app: kafka
spec:
  clusterIP: None
  ports:
  - port: 9092
    name: internal
  - port: 9093
    name: external-ssl
  - port: 9094
    name: internal-ssl
  - port: 9999
    name: jmx
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: confluent-kafka
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    targetPort: 9092
    name: internal
  - port: 9093
    targetPort: 9093
    name: external-ssl
  - port: 9094
    targetPort: 9094
    name: internal-ssl
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: confluent-kafka
  labels:
    app: kafka
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  ports:
  - port: 9093
    targetPort: 9093
    name: external-ssl
    protocol: TCP
  selector:
    app: kafka 