apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: collector
  labels:
    app: otel-collector
    component: collector
spec:
  replicas: 4
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
        component: collector
    spec:
      serviceAccountName: otel-collector
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.91.0
        command:
          - "/otelcol-contrib"
          - "--config=/etc/otel-collector-config/config.yaml"
        ports:
        - name: otlp-grpc
          containerPort: 4317
          protocol: TCP
        - name: otlp-http
          containerPort: 4318
          protocol: TCP
        - name: health-check
          containerPort: 13133
          protocol: TCP
        - name: pprof
          containerPort: 1777
          protocol: TCP
        - name: zpages
          containerPort: 55679
          protocol: TCP
        - name: metrics
          containerPort: 8888
          protocol: TCP
        env:
        - name: GOGC
          value: "80"
        - name: GOMEMLIMIT
          value: "512MiB"
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 400Mi
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /etc/otel-collector-config
        - name: otel-collector-certs-vol
          mountPath: /etc/ssl/certs
          readOnly: true
        - name: otel-collector-private-vol
          mountPath: /etc/ssl/private
          readOnly: true
        livenessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: otel-collector-config-vol
        configMap:
          name: otel-collector-config
          items:
          - key: config.yaml
            path: config.yaml
      - name: otel-collector-certs-vol
        secret:
          secretName: otel-collector-certs
          items:
          - key: client.crt
            path: client.crt
          - key: ca.crt
            path: ca.crt
      - name: otel-collector-private-vol
        secret:
          secretName: otel-collector-certs
          items:
          - key: client.key
            path: client.key
          defaultMode: 0400
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001 
