apiVersion: v1
kind: Secret
metadata:
  name: otel-collector-certs
  namespace: collector
type: Opaque
data:
  # 请将以下证书内容替换为您的实际证书（base64编码）
  # 使用命令: cat your-cert.crt | base64 -w 0
  client.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLiAoWW91ciBjbGllbnQgY2VydGlmaWNhdGUgaGVyZSkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  
  # 使用命令: cat your-key.key | base64 -w 0  
  client.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLiAoWW91ciBwcml2YXRlIGtleSBoZXJlKQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t
  
  # 使用命令: cat ca.crt | base64 -w 0
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLiAoWW91ciBDQSBjZXJ0aWZpY2F0ZSBoZXJlKQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t

---
# 如果您希望从文件创建Secret，可以使用以下命令：
# kubectl create secret generic otel-collector-certs \
#   --from-file=client.crt=path/to/client.crt \
#   --from-file=client.key=path/to/client.key \
#   --from-file=ca.crt=path/to/ca.crt \
#   -n collector 